// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/protobuf/worker.proto

package org.tensorflow.distruntime;

public final class WorkerProtos {
  private WorkerProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_GetStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_GetStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_GetStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_GetStatusResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_RegisterGraphRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_RegisterGraphRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_RegisterGraphResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_RegisterGraphResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_DeregisterGraphRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_DeregisterGraphRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_DeregisterGraphResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_DeregisterGraphResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_CleanupAllRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_CleanupAllRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_CleanupAllResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_CleanupAllResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_NamedTensor_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_NamedTensor_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_ExecutorOpts_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_ExecutorOpts_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_RunGraphRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_RunGraphRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_RunGraphResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_RunGraphResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_CleanupGraphRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_CleanupGraphRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_CleanupGraphResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_CleanupGraphResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_RecvTensorRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_RecvTensorRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_RecvTensorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_RecvTensorResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_LoggingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_LoggingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_LabeledStepStats_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_LabeledStepStats_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_LoggingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_LoggingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_TraceOpts_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_TraceOpts_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_TracingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_TracingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_TracingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tensorflow_TracingResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%tensorflow/core/protobuf/worker.proto\022" +
      "\ntensorflow\032\031google/protobuf/any.proto\032*" +
      "tensorflow/core/framework/cost_graph.pro" +
      "to\032*tensorflow/core/framework/step_stats" +
      ".proto\0321tensorflow/core/framework/device" +
      "_attributes.proto\032%tensorflow/core/frame" +
      "work/graph.proto\032&tensorflow/core/framew" +
      "ork/tensor.proto\032%tensorflow/core/protob" +
      "uf/config.proto\"\022\n\020GetStatusRequest\"L\n\021G" +
      "etStatusResponse\0227\n\021device_attributes\030\001 ",
      "\003(\0132\034.tensorflow.DeviceAttributes\"\246\001\n\024Re" +
      "gisterGraphRequest\022\026\n\016session_handle\030\001 \001" +
      "(\t\022\'\n\tgraph_def\030\002 \001(\0132\024.tensorflow.Graph" +
      "Def\022\034\n\020has_control_flow\030\003 \001(\010B\002\030\001\022/\n\rgra" +
      "ph_options\030\004 \001(\0132\030.tensorflow.GraphOptio" +
      "ns\"-\n\025RegisterGraphResponse\022\024\n\014graph_han" +
      "dle\030\001 \001(\t\".\n\026DeregisterGraphRequest\022\024\n\014g" +
      "raph_handle\030\001 \001(\t\"\031\n\027DeregisterGraphResp" +
      "onse\"&\n\021CleanupAllRequest\022\021\n\tcontainer\030\001" +
      " \003(\t\"\024\n\022CleanupAllResponse\"@\n\013NamedTenso",
      "r\022\013\n\003key\030\001 \001(\t\022$\n\003val\030\002 \001(\0132\027.tensorflow" +
      ".TensorProto\"=\n\014ExecutorOpts\022\024\n\014record_c" +
      "osts\030\001 \001(\010\022\027\n\017record_timeline\030\003 \001(\010\"\317\001\n\017" +
      "RunGraphRequest\022\024\n\014graph_handle\030\001 \001(\t\022\017\n" +
      "\007step_id\030\002 \001(\003\022+\n\texec_opts\030\005 \001(\0132\030.tens" +
      "orflow.ExecutorOpts\022%\n\004send\030\003 \003(\0132\027.tens" +
      "orflow.NamedTensor\022\020\n\010recv_key\030\004 \003(\t\022\022\n\n" +
      "is_partial\030\006 \001(\010\022\033\n\023is_last_partial_run\030" +
      "\007 \001(\010\"\222\001\n\020RunGraphResponse\022%\n\004recv\030\001 \003(\013" +
      "2\027.tensorflow.NamedTensor\022)\n\nstep_stats\030",
      "\002 \001(\0132\025.tensorflow.StepStats\022,\n\ncost_gra" +
      "ph\030\003 \001(\0132\030.tensorflow.CostGraphDef\"&\n\023Cl" +
      "eanupGraphRequest\022\017\n\007step_id\030\001 \001(\003\"\026\n\024Cl" +
      "eanupGraphResponse\"\266\001\n\021RecvTensorRequest" +
      "\022\017\n\007step_id\030\001 \001(\003\022\026\n\016rendezvous_key\030\002 \001(" +
      "\t\022\016\n\006dma_ok\030\003 \001(\010\0223\n\017client_locality\030\004 \001" +
      "(\0132\032.tensorflow.DeviceLocality\0223\n\017server" +
      "_locality\030\005 \001(\0132\032.tensorflow.DeviceLocal" +
      "ity\"\232\001\n\022RecvTensorResponse\022\'\n\006tensor\030\001 \001" +
      "(\0132\027.tensorflow.TensorProto\022\017\n\007is_dead\030\002",
      " \001(\010\022\031\n\021send_start_micros\030\003 \001(\003\022/\n\021trans" +
      "port_options\030\004 \001(\0132\024.google.protobuf.Any" +
      "\"K\n\016LoggingRequest\022\023\n\013rpc_logging\030\001 \001(\010\022" +
      "\r\n\005clear\030\002 \001(\010\022\025\n\rfetch_step_id\030\003 \003(\003\"N\n" +
      "\020LabeledStepStats\022\017\n\007step_id\030\001 \001(\003\022)\n\nst" +
      "ep_stats\030\002 \001(\0132\025.tensorflow.StepStats\"=\n" +
      "\017LoggingResponse\022*\n\004step\030\001 \003(\0132\034.tensorf" +
      "low.LabeledStepStats\"\253\001\n\tTraceOpts\022\020\n\010du" +
      "ration\030\001 \001(\001\022\031\n\021use_step_profiler\030\002 \001(\010\022" +
      "\033\n\023use_kernel_profiler\030\003 \001(\010\022\035\n\025use_exte",
      "nded_profiler\030\004 \001(\010\022\030\n\020use_gpu_profiler\030" +
      "\005 \001(\010\022\033\n\023use_sample_profiler\030\006 \001(\010\"8\n\016Tr" +
      "acingRequest\022&\n\007options\030\001 \001(\0132\025.tensorfl" +
      "ow.TraceOpts\"\021\n\017TracingResponseB/\n\032org.t" +
      "ensorflow.distruntimeB\014WorkerProtosP\001\370\001\001" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
          org.tensorflow.framework.CostGraphProtos.getDescriptor(),
          org.tensorflow.framework.StepStatsProtos.getDescriptor(),
          org.tensorflow.framework.DeviceAttributesProtos.getDescriptor(),
          org.tensorflow.framework.GraphProtos.getDescriptor(),
          org.tensorflow.framework.TensorProtos.getDescriptor(),
          org.tensorflow.framework.ConfigProtos.getDescriptor(),
        }, assigner);
    internal_static_tensorflow_GetStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tensorflow_GetStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_GetStatusRequest_descriptor,
        new java.lang.String[] { });
    internal_static_tensorflow_GetStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tensorflow_GetStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_GetStatusResponse_descriptor,
        new java.lang.String[] { "DeviceAttributes", });
    internal_static_tensorflow_RegisterGraphRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_tensorflow_RegisterGraphRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_RegisterGraphRequest_descriptor,
        new java.lang.String[] { "SessionHandle", "GraphDef", "HasControlFlow", "GraphOptions", });
    internal_static_tensorflow_RegisterGraphResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_tensorflow_RegisterGraphResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_RegisterGraphResponse_descriptor,
        new java.lang.String[] { "GraphHandle", });
    internal_static_tensorflow_DeregisterGraphRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_tensorflow_DeregisterGraphRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_DeregisterGraphRequest_descriptor,
        new java.lang.String[] { "GraphHandle", });
    internal_static_tensorflow_DeregisterGraphResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_tensorflow_DeregisterGraphResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_DeregisterGraphResponse_descriptor,
        new java.lang.String[] { });
    internal_static_tensorflow_CleanupAllRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_tensorflow_CleanupAllRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_CleanupAllRequest_descriptor,
        new java.lang.String[] { "Container", });
    internal_static_tensorflow_CleanupAllResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_tensorflow_CleanupAllResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_CleanupAllResponse_descriptor,
        new java.lang.String[] { });
    internal_static_tensorflow_NamedTensor_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_tensorflow_NamedTensor_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_NamedTensor_descriptor,
        new java.lang.String[] { "Key", "Val", });
    internal_static_tensorflow_ExecutorOpts_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_tensorflow_ExecutorOpts_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_ExecutorOpts_descriptor,
        new java.lang.String[] { "RecordCosts", "RecordTimeline", });
    internal_static_tensorflow_RunGraphRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_tensorflow_RunGraphRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_RunGraphRequest_descriptor,
        new java.lang.String[] { "GraphHandle", "StepId", "ExecOpts", "Send", "RecvKey", "IsPartial", "IsLastPartialRun", });
    internal_static_tensorflow_RunGraphResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_tensorflow_RunGraphResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_RunGraphResponse_descriptor,
        new java.lang.String[] { "Recv", "StepStats", "CostGraph", });
    internal_static_tensorflow_CleanupGraphRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_tensorflow_CleanupGraphRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_CleanupGraphRequest_descriptor,
        new java.lang.String[] { "StepId", });
    internal_static_tensorflow_CleanupGraphResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_tensorflow_CleanupGraphResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_CleanupGraphResponse_descriptor,
        new java.lang.String[] { });
    internal_static_tensorflow_RecvTensorRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_tensorflow_RecvTensorRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_RecvTensorRequest_descriptor,
        new java.lang.String[] { "StepId", "RendezvousKey", "DmaOk", "ClientLocality", "ServerLocality", });
    internal_static_tensorflow_RecvTensorResponse_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_tensorflow_RecvTensorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_RecvTensorResponse_descriptor,
        new java.lang.String[] { "Tensor", "IsDead", "SendStartMicros", "TransportOptions", });
    internal_static_tensorflow_LoggingRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_tensorflow_LoggingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_LoggingRequest_descriptor,
        new java.lang.String[] { "RpcLogging", "Clear", "FetchStepId", });
    internal_static_tensorflow_LabeledStepStats_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_tensorflow_LabeledStepStats_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_LabeledStepStats_descriptor,
        new java.lang.String[] { "StepId", "StepStats", });
    internal_static_tensorflow_LoggingResponse_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_tensorflow_LoggingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_LoggingResponse_descriptor,
        new java.lang.String[] { "Step", });
    internal_static_tensorflow_TraceOpts_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_tensorflow_TraceOpts_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_TraceOpts_descriptor,
        new java.lang.String[] { "Duration", "UseStepProfiler", "UseKernelProfiler", "UseExtendedProfiler", "UseGpuProfiler", "UseSampleProfiler", });
    internal_static_tensorflow_TracingRequest_descriptor =
      getDescriptor().getMessageTypes().get(20);
    internal_static_tensorflow_TracingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_TracingRequest_descriptor,
        new java.lang.String[] { "Options", });
    internal_static_tensorflow_TracingResponse_descriptor =
      getDescriptor().getMessageTypes().get(21);
    internal_static_tensorflow_TracingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tensorflow_TracingResponse_descriptor,
        new java.lang.String[] { });
    com.google.protobuf.AnyProto.getDescriptor();
    org.tensorflow.framework.CostGraphProtos.getDescriptor();
    org.tensorflow.framework.StepStatsProtos.getDescriptor();
    org.tensorflow.framework.DeviceAttributesProtos.getDescriptor();
    org.tensorflow.framework.GraphProtos.getDescriptor();
    org.tensorflow.framework.TensorProtos.getDescriptor();
    org.tensorflow.framework.ConfigProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
