# Default values for mnist-demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: docker.io/rivernet/mnist-demo
  tag: 4.1
  pullPolicy: IfNotPresent
service:
  type: NodePort
resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi

